// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionAppApi.Data;

#nullable disable

namespace NutritionAppApi.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    partial class NutritionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NutritionAppApi.Models.DietPreference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PreferenceId"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("BudgetLevel")
                        .HasColumnType("int");

                    b.Property<int>("DietType")
                        .HasColumnType("int");

                    b.Property<string>("ExcludedFoods")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PreferenceId");

                    b.ToTable("DietPref");
                });

            modelBuilder.Entity("NutritionAppApi.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealId"));

                    b.Property<int>("BudgetLevel")
                        .HasColumnType("int");

                    b.Property<float>("Calories")
                        .HasColumnType("float");

                    b.Property<float>("Carbs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DietArchitecture")
                        .HasColumnType("int");

                    b.Property<float>("Fats")
                        .HasColumnType("float");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("PortionSize")
                        .HasColumnType("int");

                    b.Property<float>("Protein")
                        .HasColumnType("float");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("MealId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("NutritionAppApi.Models.MealLog", b =>
                {
                    b.Property<int>("MealLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFromAI")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("LoggedCalories")
                        .HasColumnType("float");

                    b.Property<float?>("LoggedCarbs")
                        .HasColumnType("float");

                    b.Property<float?>("LoggedFats")
                        .HasColumnType("float");

                    b.Property<float?>("LoggedProtein")
                        .HasColumnType("float");

                    b.Property<int?>("MealId")
                        .HasColumnType("int");

                    b.Property<string>("MealName")
                        .HasColumnType("longtext");

                    b.Property<float?>("PortionMultiplier")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MealLogId");

                    b.HasIndex("MealId");

                    b.ToTable("LoggedMeals");
                });

            modelBuilder.Entity("NutritionAppApi.Models.MealPlan", b =>
                {
                    b.Property<int>("MealPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealPlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("TotalCalories")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MealPlanId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("NutritionAppApi.Models.MealPlanItem", b =>
                {
                    b.Property<int>("MealPlanItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealPlanItemId"));

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<int>("OptionNumber")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("PortionMultiplier")
                        .HasColumnType("float");

                    b.HasKey("MealPlanItemId");

                    b.HasIndex("MealId");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlanItem");
                });

            modelBuilder.Entity("NutritionAppApi.Models.PhotoAnalysis", b =>
                {
                    b.Property<int>("PhotoAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PhotoAnalysisId"));

                    b.Property<string>("AIServiceUsed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AnalysisRawResponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetectedFoods")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<float>("EstimatedCalories")
                        .HasColumnType("float");

                    b.Property<float>("EstimatedCarbs")
                        .HasColumnType("float");

                    b.Property<float>("EstimatedFats")
                        .HasColumnType("float");

                    b.Property<float>("EstimatedProtein")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MealLogId")
                        .HasColumnType("int");

                    b.Property<float?>("UserAdjustedCalories")
                        .HasColumnType("float");

                    b.Property<float?>("UserAdjustedCarbs")
                        .HasColumnType("float");

                    b.Property<float?>("UserAdjustedFats")
                        .HasColumnType("float");

                    b.Property<float?>("UserAdjustedProtein")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PhotoAnalysisId");

                    b.ToTable("PhotoAnalyses");
                });

            modelBuilder.Entity("NutritionAppApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutritionAppApi.Models.UserProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("DailyCalorieTarget")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("Height")
                        .HasColumnType("float");

                    b.Property<float>("TargetWeight")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("NutritionAppApi.Models.UserSettings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SettingsId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DailyCalorieReminder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MealReminderEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PreferredUnits")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SettingsId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("NutritionAppApi.Models.WeightLog", b =>
                {
                    b.Property<int>("WeightLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WeightLogId"));

                    b.Property<float?>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("MuscleMass")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<float?>("WaistCircumference")
                        .HasColumnType("float");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("WeightLogId");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("NutritionAppApi.Models.MealLog", b =>
                {
                    b.HasOne("NutritionAppApi.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionAppApi.Models.MealPlanItem", b =>
                {
                    b.HasOne("NutritionAppApi.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionAppApi.Models.MealPlan", "MealPlan")
                        .WithMany("MealPlanItems")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("NutritionAppApi.Models.UserProfile", b =>
                {
                    b.HasOne("NutritionAppApi.Models.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("NutritionAppApi.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionAppApi.Models.MealPlan", b =>
                {
                    b.Navigation("MealPlanItems");
                });

            modelBuilder.Entity("NutritionAppApi.Models.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
